-- Corrige le trigger auth qui journalisait en boucle :
--   relation "public.signup_alerts" does not exist
--
-- Ce script est idempotent. Il recrée la file publique minimale utilisée par
-- le trigger auth.users puis remplace la fonction par une version sûre.

create table if not exists public.signup_alerts (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  email text,
  phone text,
  raw_user_meta_data jsonb not null default '{}'::jsonb,
  app_metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  processed_at timestamptz,
  processing_error text
);

create unique index if not exists signup_alerts_user_id_unique
  on public.signup_alerts (user_id);

alter table public.signup_alerts enable row level security;
revoke all on table public.signup_alerts from anon, authenticated;
grant all on table public.signup_alerts to service_role;
grant usage, select on sequence public.signup_alerts_id_seq to service_role;

create or replace function public.handle_new_auth_user_alert()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  insert into public.signup_alerts (
    user_id,
    email,
    phone,
    raw_user_meta_data,
    app_metadata,
    created_at
  )
  values (
    new.id,
    new.email,
    new.phone,
    coalesce(new.raw_user_meta_data, '{}'::jsonb),
    coalesce(new.raw_app_meta_data, '{}'::jsonb),
    coalesce(new.created_at, now())
  )
  on conflict (user_id) do nothing;

  return new;
exception
  when others then
    -- Une alerte ne doit jamais empêcher la création du compte.
    raise warning 'Error signup alert: %', sqlerrm;
    return new;
end;
$$;

comment on table public.signup_alerts is
  'File technique des nouvelles inscriptions auth, destinée au webhook iNrCy.';
