export function buildDashboardPanelProps(a: any) {
  const siteWebPanelProps = {
    siteWebAllGreen: a.siteWebAllGreen,
    hasSiteWebUrl: a.hasSiteWebUrl,
    siteWebUrl: a.siteWebUrl,
    setSiteWebUrl: a.setSiteWebUrl,
    saveSiteWebUrl: a.saveSiteWebUrlFromDrawer,
    deleteSiteWebUrl: a.deleteSiteWebUrlFromDrawer,
    siteWebUrlBusy: a.isDrawerMutationPending("site_web:url:save") || a.isDrawerMutationPending("site_web:url:delete"),
    draftSiteWebUrlMeta: a.draftSiteWebUrlMeta,
    siteWebUrlNotice: a.siteWebUrlNotice,
    siteWebGa4Connected: a.siteWebGa4Connected,
    siteWebGa4MeasurementId: a.siteWebGa4MeasurementId,
    siteWebGa4PropertyId: a.siteWebGa4PropertyId,
    disconnectSiteWebGa4: a.disconnectSiteWebGa4FromDrawer,
    siteWebGa4Busy: a.isDrawerMutationPending("site_web:ga4:disconnect"),
    connectSiteWebGa4: a.connectSiteWebGa4,
    canConnectSiteWebGoogle: a.canConnectSiteWebGoogle,
    siteWebGa4Notice: a.siteWebGa4Notice,
    siteWebGscConnected: a.siteWebGscConnected,
    siteWebGscProperty: a.siteWebGscProperty,
    disconnectSiteWebGsc: a.disconnectSiteWebGscFromDrawer,
    siteWebGscBusy: a.isDrawerMutationPending("site_web:gsc:disconnect"),
    connectSiteWebGsc: a.connectSiteWebGsc,
    siteWebGscNotice: a.siteWebGscNotice,
    siteWebActusLayout: a.siteWebActusLayout,
    setSiteWebActusLayout: a.setSiteWebActusLayout,
    siteWebActusLimit: a.siteWebActusLimit,
    setSiteWebActusLimit: a.setSiteWebActusLimit,
    siteWebActusFont: a.siteWebActusFont,
    setSiteWebActusFont: a.setSiteWebActusFont,
    siteWebActusTheme: a.siteWebActusTheme,
    setSiteWebActusTheme: a.setSiteWebActusTheme,
    siteWebSavedUrl: a.siteWebSavedUrl,
    widgetTokenSiteWeb: a.widgetTokenSiteWeb,
    showSiteWebWidgetCode: a.showSiteWebWidgetCode,
    setShowSiteWebWidgetCode: a.setShowSiteWebWidgetCode,
    siteWebSettingsError: a.siteWebSettingsError,
    resetSiteWebAll: a.resetSiteWebAll,
  };

  const gmbPanelProps = {
    gmbConnected: a.gmbConnected,
    gmbAccountConnected: a.gmbAccountConnected,
    gmbConnectionStatus: a.gmbConnectionStatus,
    gmbAccountEmail: a.gmbAccountEmail,
    connectGmbAccount: a.connectGmbAccount,
    disconnectGmbAccount: a.disconnectGmbAccountFromDrawer,
    gmbAccountBusy: a.isDrawerMutationPending("gmb:account:disconnect"),
    gmbConfigured: a.gmbConfigured,
    gmbAccountName: a.gmbAccountName,
    gmbAccounts: a.gmbAccounts,
    gmbLoadingList: a.gmbLoadingList,
    loadGmbAccountsAndLocations: a.loadGmbAccountsAndLocations,
    gmbLocationName: a.gmbLocationName,
    gmbLocationLabel: a.gmbLocationLabel,
    setGmbLocationName: a.setGmbLocationName,
    gmbLocations: a.gmbLocations,
    saveGmbLocation: a.saveGmbLocationFromDrawer,
    gmbLocationBusy: a.isDrawerMutationPending("gmb:location:save") || a.isDrawerMutationPending("gmb:location:disconnect"),
    gmbLocationAction: a.isDrawerMutationPending("gmb:location:disconnect") ? "disconnect" : a.isDrawerMutationPending("gmb:location:save") ? "connect" : null,
    gmbListError: a.gmbListError,
    gmbUrl: a.gmbUrl,
    gmbUrlNotice: a.gmbUrlNotice,
    gmbUrlError: a.gmbUrlError,
    disconnectGmbBusiness: a.disconnectGmbBusinessFromDrawer,
  };

  const linkedinPanelProps = {
    linkedinConnected: a.linkedinConnected,
    linkedinAccountConnected: a.linkedinAccountConnected,
    linkedinConnectionStatus: a.linkedinConnectionStatus,
    linkedinDisplayName: a.linkedinDisplayName,
    connectLinkedinAccount: a.connectLinkedinAccount,
    disconnectLinkedinAccount: a.disconnectLinkedinAccountFromDrawer,
    linkedinAccountBusy: a.isDrawerMutationPending("linkedin:account:disconnect"),
    linkedinUrl: a.linkedinUrl,
    setLinkedinUrl: a.setLinkedinUrl,
    saveLinkedinProfileUrl: a.saveLinkedinProfileUrlFromDrawer,
    linkedinUrlBusy: a.isDrawerMutationPending("linkedin:url:save"),
    linkedinUrlNotice: a.linkedinUrlNotice,
    linkedinUrlError: a.linkedinUrlError,
    setLinkedinUrlNotice: a.setLinkedinUrlNotice,
    linkedinOrganizations: a.linkedinOrganizations,
    linkedinOrganizationsLoading: a.linkedinOrganizationsLoading,
    linkedinSelectedOrganizationId: a.linkedinSelectedOrganizationId,
    linkedinSelectedOrganizationName: a.linkedinSelectedOrganizationName,
    loadLinkedinOrganizations: a.loadLinkedinOrganizations,
    selectLinkedinOrganization: a.selectLinkedinOrganization,
    useLinkedinPersonalProfile: a.useLinkedinPersonalProfile,
  };

  const siteInrcyPanelProps = {
    siteInrcyOwnership: a.siteInrcyOwnership,
    siteInrcyAllGreen: a.siteInrcyAllGreen,
    siteInrcyContactEmail: a.siteInrcyContactEmail,
    hasSiteInrcyUrl: a.hasSiteInrcyUrl,
    siteInrcyUrl: a.siteInrcyUrl,
    setSiteInrcyUrl: a.setSiteInrcyUrl,
    saveSiteInrcyUrl: a.saveSiteInrcyUrlFromDrawer,
    deleteSiteInrcyUrl: a.deleteSiteInrcyUrlFromDrawer,
    siteInrcyUrlBusy: a.isDrawerMutationPending("site_inrcy:url:save") || a.isDrawerMutationPending("site_inrcy:url:delete"),
    draftSiteInrcyUrlMeta: a.draftSiteInrcyUrlMeta,
    siteInrcyUrlNotice: a.siteInrcyUrlNotice,
    siteInrcyGa4Connected: a.siteInrcyGa4Connected,
    ga4MeasurementId: a.ga4MeasurementId,
    ga4PropertyId: a.ga4PropertyId,
    disconnectSiteInrcyGa4: a.disconnectSiteInrcyGa4FromDrawer,
    siteInrcyGa4Busy: a.isDrawerMutationPending("site_inrcy:ga4:disconnect"),
    connectSiteInrcyGa4: a.connectSiteInrcyGa4,
    canConnectSiteInrcyGoogle: a.canConnectSiteInrcyGoogle,
    canConfigureSite: a.canConfigureSite,
    siteInrcyGa4Notice: a.siteInrcyGa4Notice,
    siteInrcyGscConnected: a.siteInrcyGscConnected,
    gscProperty: a.gscProperty,
    disconnectSiteInrcyGsc: a.disconnectSiteInrcyGscFromDrawer,
    siteInrcyGscBusy: a.isDrawerMutationPending("site_inrcy:gsc:disconnect"),
    connectSiteInrcyGsc: a.connectSiteInrcyGsc,
    siteInrcyGscNotice: a.siteInrcyGscNotice,
    siteInrcyActusLayout: a.siteInrcyActusLayout,
    setSiteInrcyActusLayout: a.setSiteInrcyActusLayout,
    siteInrcyActusLimit: a.siteInrcyActusLimit,
    setSiteInrcyActusLimit: a.setSiteInrcyActusLimit,
    siteInrcyActusFont: a.siteInrcyActusFont,
    setSiteInrcyActusFont: a.setSiteInrcyActusFont,
    siteInrcyActusTheme: a.siteInrcyActusTheme,
    setSiteInrcyActusTheme: a.setSiteInrcyActusTheme,
    siteInrcySavedUrl: a.siteInrcySavedUrl,
    widgetTokenInrcySite: a.widgetTokenInrcySite,
    showSiteInrcyWidgetCode: a.showSiteInrcyWidgetCode,
    setShowSiteInrcyWidgetCode: a.setShowSiteInrcyWidgetCode,
    siteInrcySettingsError: a.siteInrcySettingsError,
    resetSiteInrcyAll: a.resetSiteInrcyAll,
  };

  const instagramPanelProps = {
    instagramConnected: a.instagramConnected,
    instagramAccountConnected: a.instagramAccountConnected,
    instagramConnectionStatus: a.instagramConnectionStatus,
    instagramUsername: a.instagramUsername,
    connectInstagramAccount: a.connectInstagramAccount,
    connectInstagramBusinessAccount: a.connectInstagramBusinessAccount,
    disconnectInstagramAccount: a.disconnectInstagramAccountFromDrawer,
    instagramAccountBusy: a.isDrawerMutationPending("instagram:account:disconnect"),
    igAccountsLoading: a.igAccountsLoading,
    loadInstagramAccounts: a.loadInstagramAccounts,
    igSelectedPageId: a.igSelectedPageId,
    setIgSelectedPageId: a.setIgSelectedPageId,
    igAccounts: a.igAccounts,
    saveInstagramProfile: a.saveInstagramProfileFromDrawer,
    instagramProfileBusy: a.isDrawerMutationPending("instagram:profile:save") || a.isDrawerMutationPending("instagram:profile:disconnect"),
    instagramProfileAction: a.isDrawerMutationPending("instagram:profile:disconnect") ? "disconnect" : a.isDrawerMutationPending("instagram:profile:save") ? "connect" : null,
    igAccountsError: a.igAccountsError,
    instagramUrl: a.instagramUrl,
    instagramUrlNotice: a.instagramUrlNotice,
    instagramUrlError: a.instagramUrlError,
    disconnectInstagramProfile: a.disconnectInstagramProfileFromDrawer,
  };

  const facebookPanelProps = {
    facebookPageConnected: a.facebookPageConnected,
    facebookAccountConnected: a.facebookAccountConnected,
    facebookConnectionStatus: a.facebookConnectionStatus,
    facebookAccountEmail: a.facebookAccountEmail,
    connectFacebookAccount: a.connectFacebookAccount,
    connectFacebookBusinessAccount: a.connectFacebookBusinessAccount,
    disconnectFacebookAccount: a.disconnectFacebookAccountFromDrawer,
    facebookAccountBusy: a.isDrawerMutationPending("facebook:account:disconnect"),
    fbPagesLoading: a.fbPagesLoading,
    loadFacebookPages: a.loadFacebookPages,
    fbSelectedPageId: a.fbSelectedPageId,
    fbSelectedPageName: a.fbSelectedPageName,
    setFbSelectedPageId: a.setFbSelectedPageId,
    fbPages: a.fbPages,
    saveFacebookPage: a.saveFacebookPageFromDrawer,
    facebookPageBusy: a.isDrawerMutationPending("facebook:page:save") || a.isDrawerMutationPending("facebook:page:disconnect"),
    facebookPageAction: a.isDrawerMutationPending("facebook:page:disconnect") ? "disconnect" : a.isDrawerMutationPending("facebook:page:save") ? "connect" : null,
    fbPagesError: a.fbPagesError,
    facebookUrl: a.facebookUrl,
    facebookUrlNotice: a.facebookUrlNotice,
    facebookUrlError: a.facebookUrlError,
    disconnectFacebookPage: a.disconnectFacebookPageFromDrawer,
  };

  return { siteWebPanelProps, gmbPanelProps, linkedinPanelProps, siteInrcyPanelProps, instagramPanelProps, facebookPanelProps };
}
